apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent
  namespace: devops-tools
  labels:
    project: homepage-api
spec:
  containers:
    - name: jnlp
      image: 'jenkins/inbound-agent:latest-jdk11'
      args: [ '\$(JENKINS_SECRET)', '\$(JENKINS_NAME)' ]
      resources:
        requests:
          memory: "384Mi"
          cpu: "1"
        limits:
          memory: "768Mi"
          cpu: "1"
    - name: gradle
      image: ibm-semeru-runtimes:open-18.0.2_9-jdk-focal
      command:
        - cat
      tty: true
      resources:
        requests:
          memory: "512Mi"
          cpu: "100m"
        limits:
          memory: "1536Mi"
          cpu: "1"
    - name: docker
      image: docker
      tty: true
      securityContext:
        privileged: true
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "200m"
      volumeMounts:
        - name: configuration
          mountPath: /root/.docker
  volumes:
    - name: configuration
      secret:
        secretName: docker-reg-secret