apiVersion: v1
kind: Pod
metadata:
  namespace: devops-tools
spec:
  containers:
    - name: gradle
      image: ibm-semeru-runtimes:open-18.0.2_9-jdk-focal
      command:
        - cat
      tty: true
      resources:
        requests:
          memory: "512Mi"
          cpu: "100m"
        limits:
          memory: "1536Mi"
          cpu: "1"
    - name: docker
      image: docker:latest
      tty: true
      securityContext:
        privileged: true
        runAsUser: 0
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "200m"
      volumeMounts:
        - name: dockersock
          mountPath: "/var/run/docker.sock"
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock