auth0:
  audience: homepage-sebastian-api
  domain: domain
spring:
  data:
    mongodb:
      uri: uri
      database: homepage
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${auth0.domain}/