auth0:
  audience: ${AUTH0_AUDIENCE}
  domain: ${AUTH0_DOMAIN}
spring:
  data:
    mongodb:
      uri: ${DATABASE_URL}
      database: ${DATABASE_NAME}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${auth0.domain}/