apiVersion: v1
kind: Service
metadata:
  name: homepage-api-service #name of the resource that is created
  namespace: homepage
spec:
  selector:
    app: homepage-api
  ports:
    - port: 4000 #Port that the service is running on in the cluster
      protocol: "TCP"
      targetPort: 8080 #Port exposed by the service
      nodePort: 32760
  type: NodePort